[package]
name = "latiq-control-plane"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
latiq-common = { path = "../latiq-common" }
latiq-proto = { path = "../latiq-proto" }
latiq-metrics = { path = "../latiq-metrics" }
latiq-auth = { path = "../latiq-auth" }
metrics = { workspace = true }
duckdb = { workspace = true }
tonic = { workspace = true }
prost = { workspace = true }
tokio = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
serde = { version = "1", features = ["derive"] }

[dev-dependencies]
tokio-stream = { workspace = true }
tempfile = { workspace = true }
